"""
Django settings for houm_challenge project.

Generated by 'django-admin startproject' using Django 4.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path

# Application definition
from .installed import INSTALLED_APPS
from .rest import *

BASE_DIR = Path(__file__).resolve().parent.parent


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.spatialite',
        'NAME': BASE_DIR / 'db.sqlite3',
    },
    'timeseries': {
        'TYPE': 'mongo',
        'HOST': 'localhost',
        'PORT': 27017,
        'NAME': 'series_db',
        'COLLECTION': 'tracking',
    }
}